### ISSUE TITLE
S#5408 - songrequest with no arguments shows current status

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#14]
[S#5408](https://supinic.com/data/suggestion/5408) by *zneix*

When the `sr` command is invoked with no arguments, print the current status of song requests (where they are playing - found in `sb.Config`) and the currently playing video. Do this if the state permits looking the current video up, otherwise just mention the state.

The result string should contain the video title, link and optionally (if available) the requesting user's name.

Current functionality: prints an error message that a video link should provided.

**Comment by jprochazk** [comment]
I'll do it 🚀 💯 🚮
