### ISSUE TITLE
S#5409 - Discord ↔ Twitch connection for streaminfo command

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#15]
[S#5409](https://supinic.com/data/suggestion/5409) by *haddock*

Currently, if the `si` command is invoked from Discord, the user's Discord tag is used as their username. If possible, check if the command's target user has a Discord ↔ Twitch connection set up. If they do, instead of using their Discord tag, use the connected Twitch username as the argument instead.

This issue can be closed should it not be possible to check for these connections in `discord.js` as a bot account. 

For more info on how Supibot works with the Discord platform, check out the controller file: [discord.js](https://github.com/Supinic/supibot/blob/master/controllers/discord.js)

**Comment by 5E7EN** [comment]
Unfortunately, I don't believe it is possible to fetch a Discord user's connections via a bot account.

**Comment by Supinic** [comment]
Darn, seems like we can't use this data then. Is there any official mention of this? Would be good to have the docs linked here for possible future reference.

**Comment by Supinic** [comment]
The best reference I could fin can be found in this issue thread:
https://github.com/discord-net/Discord.Net/issues/901

Since the connection can only be accessed on a per-user basis via OAuth2, this connection is something that falls outside of Supibot's scope, and could be resolved by creating some sort of verification on the website repo.
