### ISSUE TITLE
S#5423 - add new emote set to the emotecheck command

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#19]
[S#5423](https://supinic.com/data/suggestion/5423) by *slch000*

Add an emote set, as described in the suggestion. Also, include a description for these emotes as they are written for other emote sets. A fitting name would be appreciated as well (`worry` or `froge` seem like valid candidates).

**Comment by SLCH** [comment]
Please assign this issue to me FeelsDankMan
