### ISSUE TITLE
S#5430 - enhance the roll command with DnD syntax

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#21]
[S#5430](https://supinic.com/data/suggestion/5430) by *ciomka202*

Enhance the `roll` command in its `DnD` style (e.g. `$roll 1d20`) to be able to parse simple operations, such as addition or subtraction - e.g. `$roll 1d20 - 5`. I'm not sure if multiplication should but included, I'll leave that to the author. Consider that the operations can be written both with and without whitespace, so string parsing could be necessary. Only allow one operation in a command.

As such, the `number` style of command invocation (e.g. `$roll 10 15`) should not be affected at all.

**Comment by jprochazk** [comment]
I'll do this one.

I'll implement the dice notation described [here](https://en.wikipedia.org/wiki/Dice_notation), and keep the existing `$roll {min} {max}` syntax.
