### ISSUE TITLE
S#5371 - chatneighbour fails when the user just arrived in chat

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#3]
[S#5371](https://supinic.com/data/suggestion/5371) by randers

If the array of users in a given channel fetched from TMI does not contain the user who invoked the command, add them to the array.

**Comment by vijaykrishna536** [comment]
Interested @Supinic Can I work on this issue?

**Comment by Supinic** [comment]
@vijaykrishna536 assigned.

**Comment by caglapickaxe** [comment]
![image](https://user-images.githubusercontent.com/45211016/101375711-c8487480-38c0-11eb-9e8f-aeafa0308241.png)

**Comment by Supinic** [comment]
@caglapickaxe assiped (assigned)
