### ISSUE TITLE
Refactor the API used in the $weather command

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#31]
Since Darksky has been acquired by Apple and will eventually no longer be available to the open public, the `weather` command needs to be refactored to a different API before the deadline.

Requirements:
- Must be finished before 31. Dec 2021
- The API used must have a free plan, with reasonable limitations. For illustration, the `weather` command has been used cca. 34000 times over the course of 10 months, leaving the monthly usage at ~3000 requests. The chosen API must provide at least this amount of requests.
- The API must have support for searching the weather by coordinates - lattitude/longitude, as this is the data users have saved in their user data.

Roadmap:
- [x] Provide a new API, or a list of them
- [x] Discuss the pricing options and functionality with @Supinic 
- [x] Allow @Supinic to introduce a new secret `sb.Config` for the API credentials to be used in the command
- [x] Refactor the `weather` command to use the new API

**Comment by tintinmaster** [comment]
I think OpenWeather with their [One Call API](https://openweathermap.org/darksky-openweather) fits perfect.
It's made for migrating from DarkSky API and provides 1000 Calls a day and also matches the same forecast options currently present in the implementation.
If you think this API fits, I would give it a try :)

**Comment by Supinic** [comment]
Finished in a streak of commits from 44c9072d3a8e69fb56a830140251df9c6ac35eea  to 6e450a23a6d4fb874ecf7d8da857a61f31c661ca

Will test now in production, iron out some errors, extra functionality can always be added. Mostly with the weather alerts.
