### ISSUE TITLE
S#5368 - reroll twitchlotto image, if deleted from imgur

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#6]
[S#5368](https://supinic.com/data/suggestion/5368) by *kalastelija01*

If the picture in the `twitchlotto` command has been deleted from Imgur, instead of aborting the execution (and telling the user that the image is not available), simply attempt again until a valid picture is hit. Optionally, remind the user about how many rerolls have been performed this way.

**Comment by RAnders00** [comment]
I'm going to work on this
