### ISSUE TITLE
S#4050 - calculation of date deltas in commands

### ISSUE THREAD

**Issue by Supinic** [Supinic/supibot-package-manager#8]
[S#4050](https://supinic.com/data/suggestion/4050) by *agenttud*

Currently, the utils method `sb.Utils.timeDelta` calculates the difference between two days as the difference in time units. This means that one year in the resulting string represents exactly 365 days.

The issue is that this does not take into account leap years. Thus, a difference from e.g. `2020-01-01` to `2030-01-01` is displayed as `10y, 1d`. Normally, we would expect just `10y`.

This change should only concern the `accage` command, because elsewhere, we want to preserve the current functionality.

**Comment by vijayakshit** [comment]
Can I pick this please?

**Comment by zneix** [comment]
JUST do it 4Head

**Comment by vijayakshit** [comment]
@Supinic https://github.com/Supinic/supibot-package-manager/pull/12
