### ISSUE TITLE
Pipe flag does not work

### ISSUE THREAD

**Issue by 2547techno** [Supinic/supibot-package-manager#93]
[Under flags](https://github.com/Supinic/supibot-package-manager/blob/master/docs/commands.md#command-structure):
>pipe This command can be use in the [pipe](https://github.com/Supinic/supibot-package-manager/blob/master/docs/commands/pipe/index.js)` meta-command.

[`$%` command has `pipe` flag present](https://github.com/Supinic/supibot-package-manager/blob/master/commands/%25/index.js#L7) but can still be run outside of a pipe

**Comment by 2547techno** [comment]
`$%` was the first and only command I looked at so most likely more commands have them aswell

**Comment by EuleHaken** [comment]
@2547techno The `pipe` flag only tells us, that the command **can** be used inside of a pipe. But it doesn't have to be inside a pipe. E.g. you may look at the [`cookie`](https://github.com/Supinic/supibot-package-manager/blob/master/commands/cookie/index.js) command, which also has the `pipe` flag, but you could execute it outside of a pipe aswell, by just typing `$cookie`. (If I understand the issue correctly)

**Comment by 2547techno** [comment]
I seem to have read the doc incorrectly, you're right. Closing issue
